import type { ChatItem } from "./types";
import type { UsageSnapshot } from "./usage";
import { formatUsage } from "./usage";

/** Build a portable markdown journal from the in-app transcript. */
export function buildSessionMarkdown(opts: {
  cwd: string;
  sessionId: string | null;
  modelId: string | null;
  usage: UsageSnapshot;
  items: ChatItem[];
  loopName?: string | null;
  loopGoal?: string | null;
}): string {
  const now = new Date().toISOString();
  const lines: string[] = [
    `# Grok Desktop session notes`,
    ``,
    `| | |`,
    `|---|---|`,
    `| Exported | ${now} |`,
    `| Project | \`${opts.cwd}\` |`,
    `| Session | \`${opts.sessionId ?? "—"}\` |`,
    `| Model | ${opts.modelId ?? "—"} |`,
    `| Usage | ${opts.usage.turns ? formatUsage(opts.usage) : "—"} |`,
  ];

  if (opts.loopName) {
    lines.push(`| Loop | ${opts.loopName} |`);
  }
  if (opts.loopGoal) {
    lines.push(`| Goal | ${opts.loopGoal} |`);
  }

  lines.push(``, `---`, ``, `## Transcript`, ``);

  for (const item of opts.items) {
    switch (item.role) {
      case "user":
        lines.push(`### You`, ``, item.text, ``);
        break;
      case "assistant":
        lines.push(`### Grok`, ``, item.text, ``);
        break;
      case "thought":
        lines.push(`<details><summary>Thinking</summary>`, ``, item.text, ``, `</details>`, ``);
        break;
      case "tool":
        lines.push(`- **Tool** (\`${item.status}\`): ${item.title}${item.detail ? ` — ${item.detail}` : ""}`);
        break;
      case "loop":
        lines.push(``, `> ${item.text.replace(/\n/g, "\n> ")}`, ``);
        break;
      case "system":
        lines.push(`*${item.text}*`, ``);
        break;
    }
  }

  lines.push(
    ``,
    `---`,
    ``,
    `## Your notes`,
    ``,
    `_Add what you learned or still want to try:_`,
    ``,
    `- `,
    ``,
    `---`,
    ``,
    `*Generated by Grok Desktop — thin UI over xAI Grok Build.*`,
    ``,
  );

  return lines.join("\n");
}

export function wrapUpPrompt(loopName: string, goal: string, completedSteps: string[]): string {
  return [
    "STEP: Wrap-up (final).",
    `Loop: ${loopName}`,
    `Original goal: ${goal}`,
    `Steps completed: ${completedSteps.join(" → ")}`,
    "",
    "Write a clear finish package for a human who may not be an expert:",
    "1. **What shipped** — bullets of concrete outcomes (files/features).",
    "2. **How to verify** — exact commands or clicks to confirm it works.",
    "3. **What to watch** — risks, TODOs, or follow-ups.",
    "4. **Learning takeaway** — one or two sentences on what mattered technically.",
    "",
    "Keep it concise. Prefer lists over essays. Do not start new large features.",
  ].join("\n");
}
